version: "3.1"
services:

    mariadb:
      container_name: c-db
      restart: always
      image: mariadb:latest
      ports:
        - "3306:3306"
      volumes: 
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root

    pma:
      container_name: c-pma
      restart: always
      image: phpmyadmin/phpmyadmin:latest
      ports: 
        - "8080:80"
      environment: 
        - PMA_HOST=mariadb

    app:
      container_name: c-app
      build: application
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./application:/var/www/html